name: medulla-deploy
services:
  - name: minio
    image: minio/minio
    args: server /data --console-address ":9001"
    bindings:
      - name: minio0
        port: 9000
        protocol: tcp
      - name: minio1
        port: 9001
        protocol: tcp

  - name: deployer
    dockerFile: ./Dockerfile
    env:
    - name: S3_DEPLOY_BUCKET_NAME
      value: "minio_compiled"
    - name: S3_DEPLOY_FILE_NAME
      value: "release.bundle"
    - name: MINIO_ENDPOINT
      value: "minio"
    - name: MINIO_ACCESS_KEY
      value: "test"
    - name: MINIO_SECRET_ACCESS_KEY
      value: "test"
    - name: MINIO_S3_ENDPOINT
      value: "minio"
    - name: MINIO_S3_ACCESS_KEY_ID
      value: "test"
    - name: MINIO_S3_SECRET_ACCESS_KEY
      value: "test"
    bindings:
    - port: 8080
      protocol: http



